apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: kubeflix-test.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 3000
